//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer_for_Test
    {
        public int QuestionId { get; set; }
        public Nullable<int> Answer { get; set; }
        public int Id { get; set; }
        public Nullable<int> TestId { get; set; }
    
        public virtual Question_For_Test Question_For_Test { get; set; }
        public virtual Test Test { get; set; }
    }
}
