//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Lessons = new HashSet<Lesson>();
            this.Groups = new HashSet<Group>();
        }
    
        public int CourseId { get; set; }
        public Nullable<System.TimeSpan> CourseTime { get; set; }
        public string CourseName { get; set; }
        public string CourseDescribe { get; set; }
        public string Proffestion { get; set; }
        public Nullable<int> MinUseres { get; set; }
        public Nullable<int> MaxUseres { get; set; }
        public Nullable<int> IdTeacher { get; set; }
        public Nullable<int> CoursePrice { get; set; }
    
        public virtual Teacher Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lesson> Lessons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group> Groups { get; set; }
    }
}
