//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Massege_Group
    {
        public int MassegeId { get; set; }
        public Nullable<int> IdGroup { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<System.TimeSpan> MassegeTime { get; set; }
    
        public virtual Group Group { get; set; }
    }
}
