//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class shiraEntities : DbContext
    {
        public shiraEntities()
            : base("name=shiraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer_for_Test> Answer_for_Test { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<Lesson> Lesson { get; set; }
        public virtual DbSet<Massege_Group> Massege_Group { get; set; }
        public virtual DbSet<Question_For_Test> Question_For_Test { get; set; }
        public virtual DbSet<Teachar> Teachar { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<Test> Test { get; set; }
        public virtual DbSet<Test_For_Student> Test_For_Student { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<User_for_Group> User_for_Group { get; set; }
        public virtual DbSet<Useres> Useres { get; set; }
    }
}
